erreduarte
*** Found local files:
***   * /home/erreduarte/airflow/logs/dag_id=open_weather_DAG/run_id=scheduled__2024-10-06T08:00:00+00:00/task_id=Drop_Old_Values/attempt=1.log
[2024-10-06T10:02:22.568+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-06T10:02:22.627+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_weather_DAG.Drop_Old_Values scheduled__2024-10-06T08:00:00+00:00 [queued]>
[2024-10-06T10:02:22.652+0100] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_weather_DAG.Drop_Old_Values scheduled__2024-10-06T08:00:00+00:00 [queued]>
[2024-10-06T10:02:22.652+0100] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-06T10:02:22.681+0100] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): Drop_Old_Values> on 2024-10-06 08:00:00+00:00
[2024-10-06T10:02:22.685+0100] {standard_task_runner.py:72} INFO - Started process 2550370 to run task
[2024-10-06T10:02:22.689+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'open_weather_DAG', 'Drop_Old_Values', 'scheduled__2024-10-06T08:00:00+00:00', '--job-id', '758', '--raw', '--subdir', 'DAGS_FOLDER/DAG_OPEN_WEATHER.py', '--cfg-path', '/tmp/tmpcuhc2a79']
[2024-10-06T10:02:22.690+0100] {standard_task_runner.py:105} INFO - Job 758: Subtask Drop_Old_Values
[2024-10-06T10:02:22.852+0100] {task_command.py:467} INFO - Running <TaskInstance: open_weather_DAG.Drop_Old_Values scheduled__2024-10-06T08:00:00+00:00 [running]> on host erreduarte
[2024-10-06T10:02:23.103+0100] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='renanduarte' AIRFLOW_CTX_DAG_ID='open_weather_DAG' AIRFLOW_CTX_TASK_ID='Drop_Old_Values' AIRFLOW_CTX_EXECUTION_DATE='2024-10-06T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-06T08:00:00+00:00'
[2024-10-06T10:02:23.104+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-06T10:02:23.160+0100] {base.py:84} INFO - Retrieving connection 'microsoft_azure_database'
[2024-10-06T10:02:23.615+0100] {sql.py:531} INFO - Running statement: DELETE FROM 
                            dbo.OpenWeatherData
                          WHERE
                            timestamp < DATEADD(day, -1, GETDATE()); 
                            
                            , parameters: None
[2024-10-06T10:02:23.661+0100] {sql.py:540} INFO - Rows affected: 50
[2024-10-06T10:02:23.754+0100] {python.py:240} INFO - Done. Returned value was: Values >24h dropped
[2024-10-06T10:02:23.859+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-06T10:02:23.859+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=open_weather_DAG, task_id=Drop_Old_Values, run_id=scheduled__2024-10-06T08:00:00+00:00, execution_date=20241006T080000, start_date=20241006T090222, end_date=20241006T090223
[2024-10-06T10:02:23.904+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-06T10:02:23.958+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
